import Head from "next/head";
import styled from "styled-components";

const Container = styled.main`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  min-height: 100vh;
  min-width: 100vw;
`;

export default function Home() {
  return (
    <div id="browser__source__container" role="dialog" aria-modal="true">
      <Head>
        <title>Goofball 2021 Tools</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <h1>Goofball 2021</h1>
      </Container>

      <footer>Created By EmoMatt</footer>
    </div>
  );
}
